"use client";

import { useEffect, useState } from "react";
import { useParams, useRouter } from "next/navigation";
import { Quote, quoteStorage } from "@/lib/quote-storage";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Separator } from "@/components/ui/separator";
import {
    ArrowLeft,
    CalendarIcon,
    Truck,
    MapPin,
    User,
    Mail,
    Phone,
    CheckCircle,
    XCircle,
    Clock,
    Save,
    Euro,
    FileText,
    Download,
    Sparkles,
    MessageSquare
} from "lucide-react";
import { format } from "date-fns";
import { fr } from "date-fns/locale";
import { toast } from "sonner";
import Link from "next/link";
import { QuoteTimeline } from "./components/QuoteTimeline";
import { generateQuotePDF } from "@/lib/pdf-generator";
import { geminiService, EstimationResult } from "@/lib/gemini";
import {
    Dialog,
    DialogContent,
    DialogDescription,
    DialogHeader,
    DialogTitle,
    DialogFooter,
} from "@/components/ui/dialog";
import { Label } from "@/components/ui/label";

export default function QuoteModerationPage() {
    const params = useParams();
    const router = useRouter();
    const id = params.id as string;

    const [quote, setQuote] = useState<Quote | null>(null);
    const [loading, setLoading] = useState(true);

    // Editable states
    const [amount, setAmount] = useState("");
    const [notes, setNotes] = useState("");
    const [hasChanges, setHasChanges] = useState(false);

    const [aiEstimation, setAiEstimation] = useState<EstimationResult | null>(null);
    const [estimating, setEstimating] = useState(false);

    // Email Drawer State
    const [emailOpen, setEmailOpen] = useState(false);
    const [emailDraft, setEmailDraft] = useState({ subject: "", body: "" });
    const [generatingEmail, setGeneratingEmail] = useState(false);

    const handleEstimate = async () => {
        if (!quote) return;
        setEstimating(true);
        try {
            const result = await geminiService.estimateTransport(quote.pickup, quote.dropoff, quote.type);
            setAiEstimation(result);
            toast.success("Estimation générée par IA");
        } catch (error) {
            toast.error("Erreur lors de l'estimation");
        } finally {
            setEstimating(false);
        }
    };

    const handleGenerateEmail = async (type: "validation" | "refusal" | "question") => {
        if (!quote) return;
        setGeneratingEmail(true);
        setEmailOpen(true);
        setEmailDraft({ subject: "Génération en cours...", body: "" });

        try {
            const draft = await geminiService.draftEmail(type, quote.client, quote.id);
            setEmailDraft(draft);
        } catch (error) {
            toast.error("Erreur de génération d'email");
            setEmailOpen(false);
        } finally {
            setGeneratingEmail(false);
        }
    };

    const applyEstimation = () => {
        if (aiEstimation) {
            setAmount(aiEstimation.price.replace(/[^0-9,]/g, '') + "€ HT"); // Basic parsing
        }
    };



    useEffect(() => {
        const loadQuote = () => {
            if (!id) return;
            const data = quoteStorage.getById(decodeURIComponent(id));
            if (data) {
                setQuote(data);
                setAmount(data.amount || "");
                setNotes(data.notes || "");
            } else {
                toast.error("Devis introuvable");
                router.push("/admin/quotes");
            }
            setLoading(false);
        };
        loadQuote();
    }, [id, router]);

    const handleSaveChanges = () => {
        if (!quote) return;

        quoteStorage.update(
            quote.id,
            { amount, notes },
            "Mise à jour dossier" // History log message
        );

        // We need to reload to get the fresh history generated by the storage
        const updated = quoteStorage.getById(quote.id);
        if (updated) {
            setQuote(updated);
        }

        setHasChanges(false);
        toast.success("Modifications enregistrées");
    };

    const handleStatusChange = (status: Quote["status"]) => {
        if (!quote) return;

        quoteStorage.updateStatus(quote.id, status);
        setQuote(prev => prev ? { ...prev, status } : null);
        toast.success(`Statut mis à jour : ${status}`);
    };

    // Detect changes
    useEffect(() => {
        if (!quote) return;
        const isChanged = amount !== (quote.amount || "") || notes !== (quote.notes || "");
        setHasChanges(isChanged);
    }, [amount, notes, quote]);

    if (loading) return <div className="p-8 text-center text-muted-foreground">Chargement du dossier...</div>;
    if (!quote) return null;

    return (
        <div className="space-y-6 max-w-7xl mx-auto">
            {/* Header */}
            <div className="flex flex-col gap-4 md:flex-row md:items-center justify-between">
                <div className="flex items-center gap-4">
                    <Link href="/admin/quotes">
                        <Button variant="outline" size="icon" className="h-9 w-9">
                            <ArrowLeft className="h-4 w-4" />
                        </Button>
                    </Link>
                    <div>
                        <div className="flex items-center gap-3">
                            <h1 className="text-2xl font-bold tracking-tight">Dossier {quote.id}</h1>
                            <Badge
                                variant="outline"
                                className={
                                    quote.status === "Validé" ? "bg-green-500/10 text-green-600 border-green-200/50" :
                                        quote.status === "Refusé" ? "bg-red-500/10 text-red-600 border-red-200/50" :
                                            "bg-orange-500/10 text-orange-600 border-orange-200/50"
                                }
                            >
                                {quote.status}
                            </Badge>
                        </div>
                        <p className="text-muted-foreground text-sm mt-1">
                            Créé le {format(new Date(quote.date), "dd MMMM yyyy", { locale: fr })}
                        </p>
                    </div>
                </div>



                <div className="flex items-center gap-2">
                    <Button
                        variant="outline"
                        onClick={() => generateQuotePDF(quote)}
                        className="hidden md:flex"
                    >
                        <Download className="mr-2 h-4 w-4" />
                        PDF
                    </Button>

                    {hasChanges && (
                        <div className="flex items-center gap-2 animate-in fade-in slide-in-from-top-2">
                            <span className="text-sm text-muted-foreground hidden sm:inline-block">
                                Modifications non enregistrées
                            </span>
                            <Button onClick={handleSaveChanges} className="bg-primary text-primary-foreground shadow-lg hover:shadow-xl transition-all">
                                <Save className="mr-2 h-4 w-4" />
                                Enregistrer
                            </Button>
                        </div>
                    )}
                </div>
            </div>

            <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">

                {/* Left Column - Read Only Context */}
                <div className="space-y-6 lg:col-span-2">
                    {/* Itinerary Card */}
                    <Card>
                        <CardHeader className="pb-4">
                            <CardTitle className="text-lg flex items-center gap-2">
                                <MapPin className="h-5 w-5 text-primary" />
                                Itinéraire & Transport
                            </CardTitle>
                        </CardHeader>
                        <CardContent>
                            <div className="space-y-8 relative pl-6">
                                {/* Dotted Line */}
                                <div className="absolute left-6 top-3 bottom-3 w-px border-l-2 border-dashed border-muted-foreground/20" />

                                {/* Pickup */}
                                <div className="relative pl-8">
                                    <div className="absolute left-[-5px] top-0 h-4 w-4 rounded-full border-2 border-green-500 bg-background shadow-sm" />
                                    <div className="bg-muted/10 p-4 rounded-lg border">
                                        <h4 className="text-xs font-semibold text-green-600 uppercase tracking-wider mb-1">Départ</h4>
                                        <p className="font-medium text-lg">{quote.pickup}</p>
                                    </div>
                                </div>

                                {/* Dropoff */}
                                <div className="relative pl-8">
                                    <div className="absolute left-[-5px] top-0 h-4 w-4 rounded-full border-2 border-red-500 bg-background shadow-sm" />
                                    <div className="bg-muted/10 p-4 rounded-lg border">
                                        <h4 className="text-xs font-semibold text-red-600 uppercase tracking-wider mb-1">Arrivée</h4>
                                        <p className="font-medium text-lg">{quote.dropoff}</p>
                                    </div>
                                </div>
                            </div>

                            <Separator className="my-6" />

                            <div className="grid grid-cols-2 gap-4">
                                <div className="flex items-center gap-3 p-3 bg-muted/20 rounded-lg">
                                    <CalendarIcon className="h-5 w-5 text-muted-foreground" />
                                    <div>
                                        <p className="text-xs text-muted-foreground">Date Prévue</p>
                                        <p className="font-medium">
                                            {format(new Date(quote.transportDate), "dd MMM yyyy", { locale: fr })}
                                        </p>
                                    </div>
                                </div>
                                <div className="flex items-center gap-3 p-3 bg-muted/20 rounded-lg">
                                    <Truck className="h-5 w-5 text-muted-foreground" />
                                    <div>
                                        <p className="text-xs text-muted-foreground">Type de Véhicule</p>
                                        <p className="font-medium capitalize">{quote.type}</p>
                                    </div>
                                </div>
                            </div>
                        </CardContent>
                    </Card>

                    {/* Client Card */}
                    <Card>
                        <CardHeader className="pb-4">
                            <CardTitle className="text-lg flex items-center gap-2">
                                <User className="h-5 w-5 text-primary" />
                                Informations Client
                            </CardTitle>
                        </CardHeader>
                        <CardContent>
                            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                                <div>
                                    <h3 className="tex-sm font-medium text-muted-foreground mb-1">Contact Principal</h3>
                                    <p className="text-lg font-medium">{quote.client}</p>
                                </div>

                                <div className="space-y-3">
                                    <a href={`mailto:${quote.email}`} className="flex items-center gap-3 p-2 hover:bg-muted rounded-md transition-colors group">
                                        <div className="p-2 bg-primary/5 rounded-full group-hover:bg-primary/10">
                                            <Mail className="h-4 w-4 text-primary" />
                                        </div>
                                        <span className="text-sm font-medium">{quote.email}</span>
                                    </a>
                                    <a href={`tel:${quote.phone}`} className="flex items-center gap-3 p-2 hover:bg-muted rounded-md transition-colors group">
                                        <div className="p-2 bg-primary/5 rounded-full group-hover:bg-primary/10">
                                            <Phone className="h-4 w-4 text-primary" />
                                        </div>
                                        <span className="text-sm font-medium">{quote.phone}</span>
                                    </a>
                                </div>
                            </div>
                        </CardContent>
                    </Card>
                </div>

                {/* Right Column - Workspace */}
                <div className="space-y-6 text-foreground">
                    {/* Tarification */}
                    <Card className="border-l-4 border-l-primary/50 overflow-hidden">
                        <div className="absolute top-0 right-0 p-4 opacity-5">
                            <Euro className="h-24 w-24" />
                        </div>
                        <CardHeader>
                            <CardTitle className="flex items-center gap-2">
                                <Euro className="h-5 w-5" />
                                Tarification
                            </CardTitle>
                            <CardDescription>
                                Définissez le prix final ou une estimation pour le client.
                            </CardDescription>
                        </CardHeader>
                        <CardContent>
                            <div className="space-y-2">
                                <label className="text-sm font-medium">Montant (Devise incluse ex: 150€)</label>
                                <div className="flex gap-2">
                                    <Input
                                        value={amount}
                                        onChange={(e) => setAmount(e.target.value)}
                                        className="text-lg font-mono"
                                        placeholder="Ex: 450€ HT"
                                    />
                                    <Button
                                        variant="secondary"
                                        size="icon"
                                        onClick={handleEstimate}
                                        disabled={estimating}
                                        title="Estimer avec IA"
                                    >
                                        <Sparkles className={`h-4 w-4 text-purple-600 ${estimating ? "animate-pulse" : ""}`} />
                                    </Button>
                                </div>
                                {aiEstimation && (
                                    <div className="mt-4 p-3 bg-purple-500/5 border border-purple-200/20 rounded-lg text-sm space-y-2 animate-in fade-in slide-in-from-top-2">
                                        <div className="flex justify-between font-medium text-purple-700">
                                            <span>Estimation: {aiEstimation.price}</span>
                                            <span>{aiEstimation.distance} / {aiEstimation.duration}</span>
                                        </div>
                                        <p className="text-xs text-muted-foreground">{aiEstimation.reasoning}</p>
                                        <Button
                                            variant="link"
                                            className="h-auto p-0 text-purple-600 text-xs"
                                            onClick={applyEstimation}
                                        >
                                            Appliquer ce prix
                                        </Button>
                                    </div>
                                )}
                            </div>

                        </CardContent>
                    </Card>

                    {/* Notes Internes */}
                    <Card>
                        <CardHeader>
                            <CardTitle className="flex items-center gap-2">
                                <FileText className="h-5 w-5" />
                                Notes Internes
                            </CardTitle>
                            <CardDescription>
                                Visible uniquement par l'équipe admin et les chauffeurs.
                            </CardDescription>
                        </CardHeader>
                        <CardContent>
                            <Textarea
                                value={notes}
                                onChange={(e) => setNotes(e.target.value)}
                                className="min-h-[150px] resize-none focus-visible:ring-primary/20"
                                placeholder="Instructions spéciales, codes d'accès, spécificités du chargement..."
                            />
                        </CardContent>
                    </Card>

                    {/* Actions Rapides */}
                    <Card>
                        <CardHeader>
                            <CardTitle className="text-sm uppercase tracking-wider text-muted-foreground">
                                Actions
                            </CardTitle>
                        </CardHeader>
                        <CardContent className="space-y-3">
                            <Button
                                className="w-full justify-start text-green-600 bg-green-500/10 hover:bg-green-500/20 border-green-200/20 hover:border-green-300/30"
                                variant="outline"
                                onClick={() => handleStatusChange("Validé")}
                            >
                                <CheckCircle className="mr-2 h-4 w-4" />
                                Valider le devis
                            </Button>

                            <Button
                                className="w-full justify-start text-red-600 bg-red-500/10 hover:bg-red-500/20 border-red-200/20 hover:border-red-300/30"
                                variant="outline"
                                onClick={() => handleStatusChange("Refusé")}
                            >
                                <XCircle className="mr-2 h-4 w-4" />
                                Refuser le transport
                            </Button>

                            <Separator className="my-2" />

                            <Button
                                className="w-full justify-start text-orange-600 bg-orange-500/10 hover:bg-orange-500/20 border-orange-200/20 hover:border-orange-300/30"
                                variant="outline"
                                onClick={() => handleStatusChange("En attente")}
                            >
                                <Clock className="mr-2 h-4 w-4" />
                                Remettre en attente
                            </Button>

                            <Separator className="my-2" />

                            <div className="grid grid-cols-2 gap-2">
                                <Button size="sm" variant="ghost" onClick={() => handleGenerateEmail("validation")}>
                                    <Sparkles className="mr-2 h-3 w-3 text-purple-500" /> Validation
                                </Button>
                                <Button size="sm" variant="ghost" onClick={() => handleGenerateEmail("refusal")}>
                                    <Sparkles className="mr-2 h-3 w-3 text-purple-500" /> Refus
                                </Button>
                            </div>
                        </CardContent>
                    </Card>

                    {/* Historique */}
                    <Card>
                        <CardHeader>
                            <CardTitle className="text-sm uppercase tracking-wider text-muted-foreground flex items-center gap-2">
                                <Clock className="h-4 w-4" />
                                Historique
                            </CardTitle>
                        </CardHeader>
                        <CardContent>
                            <QuoteTimeline quote={quote} />
                        </CardContent>
                    </Card>
                </div>
            </div>
            {/* AI Email Dialog */}
            <Dialog open={emailOpen} onOpenChange={setEmailOpen}>
                <DialogContent className="sm:max-w-[625px]">
                    <DialogHeader>
                        <DialogTitle>Assistant de Rédaction IA</DialogTitle>
                        <DialogDescription>
                            Modifiez le brouillon généré avant de l'envoyer (Simulation).
                        </DialogDescription>
                    </DialogHeader>
                    <div className="grid gap-4 py-4">
                        <div className="grid gap-2">
                            <Label>Objet</Label>
                            <Input
                                value={emailDraft.subject}
                                onChange={(e) => setEmailDraft({ ...emailDraft, subject: e.target.value })}
                                disabled={generatingEmail}
                            />
                        </div>
                        <div className="grid gap-2">
                            <Label>Message</Label>
                            <Textarea
                                value={emailDraft.body}
                                onChange={(e) => setEmailDraft({ ...emailDraft, body: e.target.value })}
                                className="h-[200px]"
                                disabled={generatingEmail}
                            />
                        </div>
                    </div>
                    <DialogFooter>
                        <Button variant="secondary" onClick={() => setEmailOpen(false)}>Annuler</Button>
                        <Button onClick={() => {
                            toast.success("Email envoyé (Simulation)");
                            setEmailOpen(false);
                            // Log communication in history
                            if (quote) quoteStorage.addNote(quote.id, `Email envoyé: ${emailDraft.subject}`);
                        }}>
                            Envoyer
                        </Button>
                    </DialogFooter>
                </DialogContent>
            </Dialog>
        </div >
    );
}
